version: "3.8"

services:
    web:
        build:
            context: ./docker/web
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        volumes:
            - ./:/var/www/html
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
